var homophones = {
    "accept":         ["except"],
    "except":         ["accept"],
    "acclamation":    ["acclimation"],
    "acclimation":    ["acclamation"],
    "acts":           ["ax", "axe"],
    "ax":             ["acts", "axe"],
    "axe":            ["acts", "ax"],
    "adolescence":    ["adolescents"],
    "adolescents":    ["adolescence"],
    "aeration":       ["erration"],
    "erration":       ["aeration"],
    "aerie":          ["airy"],
    "airy":           ["aerie"],
    "affect":         ["effect"],
    "effect":         ["affect"],
    "aid":            ["aide"],
    "aide":           ["aid"],
    "ail":            ["ale"],
    "ale":            ["ail"],
    "air":            ["err", "ere", "heir"],
    "ere":            ["err", "air", "heir"],
    "heir":           ["err", "ere", "air"],
    "aisle":          ["I'll", "isle"],
    "I'll":           ["aisle", "isle"],
    "isle":           ["aisle", "I'll"],
    "all":            ["awl"],
    "awl":            ["all"],
    "allowed":        ["aloud"],
    "aloud":          ["allowed"],
    "allude":         ["elude"],
    "elude":          ["allude"],
    "altar":          ["alter"],
    "alter":          ["altar"],
    "appose":         ["oppose"],
    "oppose":         ["appose"],
    "arc":            ["ark"],
    "ark":            ["arc"],
    "are":            ["our"],
    "our":            ["hour"],
    "ascent":         ["assent"],
    "assent":         ["ascent"],
    "ate":            ["eight"],
    "eight":          ["ate"],
    "away":           ["aweigh"],
    "aweigh":         ["away"],
    "aye":            ["eye", "I"],
    "eye":            ["aye", "I"],
    "I":              ["aye", "eye"],
    "bade":           ["bayed"],
    "bayed":          ["bade"],
    "bail":           ["bale"],
    "bale":           ["bail"],
    "bait":           ["bate"],
    "bate":           ["bait"],
    "bald":           ["balled", "bawled"],
    "balled":         ["bald", "bawled"],
    "bawled":         ["bald", "balled"],
    "ball":           ["bawl"],
    "bawl":           ["ball"],
    "band":           ["banned"],
    "banned":         ["band"],
    "bard":           ["barred"],
    "barred":         ["bard"],
    "bare":           ["bear"],
    "bear":           ["bare"],
    "baron":          ["barren"],
    "barren":         ["baron"],
    "base":           ["bass"],
    "bass":           ["base"],
    "based":          ["baste"],
    "baste":          ["based"],
    "bazaar":         ["bizarre"],
    "bizarre":        ["bazaar"],
    "be":             ["bee"],
    "bee":            ["be"],
    "beach":          ["beech"],
    "beech":          ["beach"],
    "bean":           ["been"],
    "been":           ["bin"],
    "beat":           ["beet"],
    "beet":           ["beat"],
    "bin":            ["been"],
    "beer":           ["bier"],
    "bier":           ["beer"],
    "bell":           ["belle"],
    "belle":          ["bell"],
    "berry":          ["bury"],
    "bury":           ["berry"],
    "berth":          ["birth"],
    "birth":          ["berth"],
    "better":         ["bettor"],
    "bettor":         ["better"],
    "bight":          ["bite"],
    "bite":           ["bight"],
    "billed":         ["build"],
    "build":          ["billed"],
    "bird":           ["burred"],
    "burred":         ["bird"],
    "blew":           ["blue"],
    "blue":           ["blew"],
    "boar":           ["boor", "bore"],
    "boor":           ["boar", "bore"],
    "bore":           ["boar", "boor"],
    "board":          ["bored"],
    "bored":          ["board"],
    "boarder":        ["border"],
    "border":         ["boarder"],
    "bode":           ["bowed"],
    "bowed":          ["bode"],
    "bold":           ["bowled"],
    "bowled":         ["bold"],
    "bolder":         ["boulder", "bowlder"],
    "boulder":        ["bolder", "bowlder"],
    "bowlder":        ["bolder", "boulder"],
    "bole":           ["bowl"],
    "bowl":           ["bole"],
    "boos":           ["booze"],
    "booze":          ["boos"],
    "bough":          ["bow"],
    "bow":            ["bough"],
    "boy":            ["buoy"],
    "buoy":           ["boy"],
    "braid":          ["brayed"],
    "brayed":         ["braid"],
    "braise":         ["braize", "brays", "braze"],
    "braize":         ["braise", "brays", "braze"],
    "brays":          ["braise", "braize", "braze"],
    "braze":          ["braise", "braize", "brays"],
    "brake":          ["break"],
    "break":          ["brake"],
    "breach":         ["breech"],
    "breech":         ["breach"],
    "bread":          ["bred"],
    "bred":           ["bread"],
    "brewed":         ["brood"],
    "brood":          ["brewed"],
    "brews":          ["bruise"],
    "bruise":         ["brews"],
    "bridal":         ["bridle"],
    "bridle":         ["bridal"],
    "burro":          ["burrow"],
    "burrow":         ["burro"],
    "bus":            ["buss"],
    "buss":           ["bus"],
    "bused":          ["bust"],
    "bust":           ["bused"],
    "but":            ["butt"],
    "butt":           ["but"],
    "buy":            ["by", "bye"],
    "by":             ["buy", "bye"],
    "bye":            ["buy", "by"],
    "cache":          ["cash"],
    "cash":           ["cache"],
    "callous":        ["callus"],
    "callus":         ["callous"],
    "can't":          ["cant"],
    "cant":           ["can't"],
    "cannon":         ["canon"],
    "canon":          ["cannon"],
    "canter":         ["cantor"],
    "cantor":         ["canter"],
    "carat":          ["caret", "carrot"],
    "caret":          ["carat", "carrot"],
    "carrot":         ["carat", "caret"],
    "caries":         ["carries"],
    "carries":        ["caries"],
    "cast":           ["caste"],
    "caste":          ["cast"],
    "cede":           ["seed"],
    "seed":           ["cede"],
    "cell":           ["sell"],
    "sell":           ["cell"],
    "cellar":         ["seller"],
    "seller":         ["cellar"],
    "censor":         ["sensor"],
    "sensor":         ["censor"],
    "cent":           ["scent", "sent"],
    "scent":          ["cent", "sent"],
    "sent":           ["cent", "scent"],
    "cents":          ["scents", "sense"],
    "scents":         ["cents", "sense"],
    "sense":          ["cents", "scents"],
    "cereal":         ["serial"],
    "serial":         ["cereal"],
    "cession":        ["session"],
    "session":        ["cession"],
    "chaise":         ["chase"],
    "chase":          ["chaise"],
    "chalk":          ["chock"],
    "chock":          ["chalk"],
    "chance":         ["chants"],
    "chants":         ["chance"],
    "chased":         ["chaste"],
    "chaste":         ["chased"],
    "cheap":          ["cheep"],
    "cheep":          ["cheap"],
    "chews":          ["choose"],
    "choose":         ["chews"],
    "chic":           ["sheik"],
    "sheik":          ["shake"],
    "choir":          ["quire"],
    "quire":          ["choir"],
    "chord":          ["cord", "cored"],
    "cord":           ["chord", "cored"],
    "cored":          ["chord", "cord"],
    "chute":          ["shoot"],
    "shoot":          ["chute"],
    "cite":           ["sight", "site"],
    "sight":          ["cite", "site"],
    "site":           ["cite", "sight"],
    "clause":         ["claws"],
    "claws":          ["clause"],
    "click":          ["clique"],
    "clique":         ["click"],
    "close":          ["clothes"],
    "clothes":        ["close"],
    "coal":           ["cole"],
    "cole":           ["coal"],
    "coaled":         ["cold"],
    "cold":           ["coaled"],
    "coarse":         ["course"],
    "course":         ["coarse"],
    "coated":         ["coded"],
    "coded":          ["coated"],
    "cocks":          ["cox"],
    "cox":            ["cocks"],
    "complement":     ["compliment"],
    "compliment":     ["complement"],
    "contingence":    ["contingents"],
    "contingents":    ["contingence"],
    "coo":            ["coup"],
    "coup":           ["coo"],
    "coop":           ["coupe"],
    "coupe":          ["coop"],
    "correspondence": ["correspondents"],
    "correspondents": ["correspondence"],
    "cosign":         ["cosine"],
    "cosine":         ["cosign"],
    "council":        ["counsel"],
    "counsel":        ["council"],
    "councilor":      ["counselor"],
    "counselor":      ["councilor"],
    "creak":          ["creek"],
    "creek":          ["creak"],
    "crewed":         ["crude"],
    "crude":          ["crewed"],
    "crews":          ["cruise"],
    "cruise":         ["crews"],
    "cue":            ["queue"],
    "queue":          ["cue"],
    "currant":        ["current"],
    "current":        ["currant"],
    "curser":         ["cursor"],
    "cursor":         ["curser"],
    "dam":            ["damn"],
    "damn":           ["dam"],
    "Dane":           ["deign"],
    "deign":          ["Dane"],
    "days":           ["daze"],
    "daze":           ["days"],
    "dear":           ["deer"],
    "deer":           ["dear"],
    "dense":          ["dents"],
    "dents":          ["dense"],
    "dependence":     ["dependents"],
    "dependents":     ["dependence"],
    "dew":            ["do", "due"],
    "do":             ["dew", "due"],
    "due":            ["dew", "do"],
    "die":            ["dye"],
    "dye":            ["die"],
    "dire":           ["dyer"],
    "dyer":           ["dire"],
    "discreet":       ["discrete"],
    "discrete":       ["discreet"],
    "doe":            ["dough"],
    "dough":          ["doe"],
    "does":           ["doughs", "doze"],
    "doughs":         ["does", "doze"],
    "doze":           ["does", "doughs"],
    "done":           ["dun"],
    "dun":            ["done"],
    "dual":           ["duel"],
    "duel":           ["dual"],
    "ducked":         ["duct"],
    "duct":           ["ducked"],
    "earn":           ["urn"],
    "urn":            ["earn"],
    "either":         ["ether"],
    "ether":          ["either"],
    "emigrant":       ["immigrant"],
    "immigrant":      ["emigrant"],
    "ensure":         ["insure"],
    "insure":         ["ensure"],
    "eutopia":        ["utopia"],
    "utopia":         ["eutopia"],
    "ewe":            ["yew", "you"],
    "yew":            ["ewe", "you"],
    "you":            ["ewe", "yew"],
    "eyed":           ["I'd"],
    "I'd":            ["eyed"],
    "fain":           ["feign"],
    "feign":          ["fain"],
    "faint":          ["feint"],
    "feint":          ["faint"],
    "fair":           ["fare"],
    "fare":           ["fair"],
    "fairy":          ["ferry"],
    "ferry":          ["fairy"],
    "fate":           ["fete"],
    "fete":           ["fate"],
    "faze":           ["phase"],
    "phase":          ["faze"],
    "feat":           ["feet"],
    "feet":           ["feat"],
    "feudal":         ["futile"],
    "futile":         ["feudal"],
    "find":           ["fined"],
    "fined":          ["find"],
    "finish":         ["Finnish"],
    "Finnish":        ["finish"],
    "fir":            ["fur"],
    "fur":            ["fir"],
    "flair":          ["flare"],
    "flare":          ["flair"],
    "flea":           ["flee"],
    "flee":           ["flea"],
    "flecks":         ["flex"],
    "flex":           ["flecks"],
    "flew":           ["flue"],
    "flue":           ["flew"],
    "flour":          ["flower"],
    "flower":         ["flour"],
    "foaled":         ["fold"],
    "fold":           ["foaled"],
    "for":            ["fore", "four"],
    "fore":           ["for", "four"],
    "four":           ["for", "fore"],
    "forego":         ["forgo"],
    "forgo":          ["forego"],
    "foreword":       ["forward"],
    "forward":        ["foreword"],
    "forth":          ["fourth"],
    "fourth":         ["forth"],
    "foul":           ["fowl"],
    "fowl":           ["foul"],
    "frees":          ["freeze", "frieze"],
    "freeze":         ["frees", "frieze"],
    "frieze":         ["frees", "freeze"],
    "friar":          ["fryer"],
    "fryer":          ["friar"],
    "gage":           ["gauge"],
    "gauge":          ["gage"],
    "gait":           ["gate"],
    "gate":           ["gait"],
    "gel":            ["jell"],
    "jell":           ["gel"],
    "gene":           ["jean"],
    "jean":           ["gene"],
    "gild":           ["guild"],
    "guild":          ["gild"],
    "gneiss":         ["nice"],
    "nice":           ["gneiss"],
    "gored":          ["gourd"],
    "gourd":          ["gored"],
    "grade":          ["grayed", "greyed"],
    "grayed":         ["grade", "greyed"],
    "greyed":         ["grade", "grayed"],
    "grate":          ["great"],
    "great":          ["grate"],
    "grays":          ["greys", "graze"],
    "greys":          ["grays", "graze"],
    "graze":          ["grays", "greys"],
    "grisly":         ["grizzly"],
    "grizzly":        ["grisly"],
    "groan":          ["grown"],
    "grown":          ["groan"],
    "guessed":        ["guest"],
    "guest":          ["guessed"],
    "guide":          ["guyed"],
    "guyed":          ["guide"],
    "guise":          ["guys"],
    "guys":           ["guise"],
    "hail":           ["hale"],
    "hale":           ["hail"],
    "hair":           ["hare"],
    "hare":           ["hair"],
    "hairy":          ["harry"],
    "harry":          ["hairy"],
    "hall":           ["haul"],
    "haul":           ["hall"],
    "halve":          ["have"],
    "have":           ["halve"],
    "hangar":         ["hanger"],
    "hanger":         ["hangar"],
    "hay":            ["hey"],
    "hey":            ["hay"],
    "hays":           ["haze"],
    "haze":           ["hays"],
    "he'd":           ["heed"],
    "heed":           ["he'd"],
    "he'll":          ["heal", "heel"],
    "heal":           ["he'll", "heel"],
    "heel":           ["he'll", "heal"],
    "hear":           ["here"],
    "here":           ["hear"],
    "heard":          ["herd"],
    "herd":           ["heard"],
    "heated":         ["heeded"],
    "heeded":         ["heated"],
    "hew":            ["hue"],
    "hue":            ["hew"],
    "hi":             ["high"],
    "high":           ["hi"],
    "higher":         ["hire"],
    "hire":           ["higher"],
    "him":            ["hymn"],
    "hymn":           ["him"],
    "ho":             ["hoe"],
    "hoe":            ["ho"],
    "hoar":           ["whore"],
    "whore":          ["hoar"],
    "hoard":          ["horde"],
    "horde":          ["hoard"],
    "hoarse":         ["horse"],
    "horse":          ["hoarse"],
    "hoes":           ["hose"],
    "hose":           ["hoes"],
    "hold":           ["holed"],
    "holed":          ["hold"],
    "hole":           ["whole"],
    "whole":          ["hole"],
    "holey":          ["holy", "wholly"],
    "holy":           ["holey", "wholly"],
    "wholly":         ["holey", "holy"],
    "hostel":         ["hostile"],
    "hostile":        ["hostel"],
    "hour":           ["our"],
    "idle":           ["idol"],
    "idol":           ["idle"],
    "immanent":       ["imminent"],
    "imminent":       ["immanent"],
    "in":             ["inn"],
    "inn":            ["in"],
    "incidence":      ["incidents"],
    "incidents":      ["incidence"],
    "incite":         ["insight"],
    "insight":        ["incite"],
    "instance":       ["instants"],
    "instants":       ["instance"],
    "intense":        ["intents"],
    "intents":        ["intense"],
    "intension":      ["intention"],
    "intention":      ["intension"],
    "it's":           ["its"],
    "its":            ["it's"],
    "jam":            ["jamb"],
    "jamb":           ["jam"],
    "knave":          ["nave"],
    "nave":           ["knave"],
    "knead":          ["kneed", "need"],
    "kneed":          ["knead", "need"],
    "need":           ["knead", "kneed"],
    "knew":           ["new"],
    "new":            ["knew"],
    "knight":         ["night"],
    "night":          ["knight"],
    "knit":           ["nit"],
    "nit":            ["knit"],
    "knot":           ["naught", "not"],
    "naught":         ["knot", "not"],
    "not":            ["knot", "naught"],
    "know":           ["no"],
    "no":             ["know"],
    "knows":          ["nose"],
    "nose":           ["knows"],
    "lacks":          ["lax"],
    "lax":            ["lacks"],
    "lade":           ["laid"],
    "laid":           ["lade"],
    "lain":           ["lane"],
    "lane":           ["lain"],
    "lair":           ["layer"],
    "layer":          ["lair"],
    "lam":            ["lamb"],
    "lamb":           ["lam"],
    "laps":           ["lapse"],
    "lapse":          ["laps"],
    "lay":            ["lei"],
    "lei":            ["lay"],
    "lays":           ["laze"],
    "laze":           ["lays"],
    "leach":          ["leech"],
    "leech":          ["leach"],
    "lead":           ["led"],
    "led":            ["lead"],
    "leak":           ["leek"],
    "leek":           ["leak"],
    "lean":           ["lien"],
    "lien":           ["lean"],
    "leased":         ["least"],
    "least":          ["leased"],
    "lends":          ["lens"],
    "lens":           ["lends"],
    "lessen":         ["lesson"],
    "lesson":         ["lessen"],
    "lesser":         ["lessor"],
    "lessor":         ["lesser"],
    "let's":          ["lets"],
    "lets":           ["let's"],
    "levee":          ["levy"],
    "levy":           ["levee"],
    "liar":           ["lyre"],
    "lyre":           ["liar"],
    "lichen":         ["liken"],
    "liken":          ["lichen"],
    "lickerish":      ["licorice"],
    "licorice":       ["lickerish"],
    "lie":            ["lye"],
    "lye":            ["lie"],
    "links":          ["lynx"],
    "lynx":           ["links"],
    "lo":             ["low"],
    "low":            ["lo"],
    "load":           ["lode"],
    "lode":           ["load"],
    "loan":           ["lone"],
    "lone":           ["loan"],
    "loch":           ["lock"],
    "lock":           ["loch"],
    "locks":          ["lox"],
    "lox":            ["locks"],
    "loop":           ["loupe"],
    "loupe":          ["loop"],
    "loos":           ["lose"],
    "lose":           ["loose"],
    "loose":          ["lose"],
    "made":           ["maid"],
    "maid":           ["made"],
    "mail":           ["male"],
    "male":           ["mail"],
    "main":           ["mane"],
    "mane":           ["main"],
    "maize":          ["Mays", "maze"],
    "Mays":           ["maize", "maze"],
    "maze":           ["maize", "Mays"],
    "mall":           ["maul"],
    "maul":           ["mall"],
    "manner":         ["manor"],
    "manor":          ["manner"],
    "marshal":        ["martial"],
    "martial":        ["marshal"],
    "massed":         ["mast"],
    "mast":           ["massed"],
    "mat":            ["matte"],
    "matte":          ["mat"],
    "mean":           ["mien"],
    "mien":           ["mean"],
    "meat":           ["meet", "mete"],
    "meet":           ["meat", "mete"],
    "mete":           ["meat", "meet"],
    "medal":          ["meddle", "metal", "mettle"],
    "meddle":         ["medal", "metal", "mettle"],
    "metal":          ["medal", "meddle", "mettle"],
    "mettle":         ["medal", "meddle", "metal"],
    "might":          ["mite"],
    "mite":           ["might"],
    "mince":          ["mints"],
    "mints":          ["mince"],
    "mind":           ["mined"],
    "mined":          ["mind"],
    "miner":          ["minor"],
    "minor":          ["miner"],
    "missed":         ["mist"],
    "mist":           ["missed"],
    "moat":           ["mote"],
    "mote":           ["moat"],
    "mood":           ["mooed"],
    "mooed":          ["mood"],
    "moor":           ["more"],
    "more":           ["moor"],
    "morning":        ["mourning"],
    "mourning":       ["morning"],
    "muscle":         ["mussel"],
    "mussel":         ["muscle"],
    "mussed":         ["must"],
    "must":           ["mussed"],
    "naval":          ["navel"],
    "navel":          ["naval"],
    "nay":            ["neigh"],
    "neigh":          ["nay"],
    "nicks":          ["nix"],
    "nix":            ["nicks"],
    "none":           ["nun"],
    "nun":            ["none"],
    "oar":            ["or", "ore"],
    "or":             ["oar", "ore"],
    "ore":            ["oar", "or"],
    "ode":            ["owed"],
    "owed":           ["ode"],
    "oh":             ["owe"],
    "owe":            ["oh"],
    "once":           ["wants"],
    "wants":          ["once"],
    "one":            ["won"],
    "won":            ["one"],
    "oohs":           ["ooze"],
    "ooze":           ["oohs"],
    "overseas":       ["oversees"],
    "oversees":       ["overseas"],
    "paced":          ["paste"],
    "paste":          ["paced"],
    "packed":         ["pact"],
    "pact":           ["packed"],
    "pail":           ["pale"],
    "pale":           ["pail"],
    "pain":           ["pane"],
    "pane":           ["pain"],
    "pair":           ["pare", "pear"],
    "pare":           ["pair", "pear"],
    "pear":           ["pair", "pare"],
    "palate":         ["palette", "pallet"],
    "palette":        ["palate", "pallet"],
    "pallet":         ["palate", "palette"],
    "parish":         ["perish"],
    "perish":         ["parish"],
    "passed":         ["past"],
    "past":           ["passed"],
    "patience":       ["patients"],
    "patients":       ["patience"],
    "pause":          ["paws"],
    "paws":           ["pause"],
    "peace":          ["piece"],
    "piece":          ["peace"],
    "peak":           ["peek", "pique"],
    "peek":           ["peak", "pique"],
    "pique":          ["peak", "peek"],
    "peal":           ["peel"],
    "peel":           ["peal"],
    "pearl":          ["purl"],
    "purl":           ["pearl"],
    "pedal":          ["peddle", "petal"],
    "peddle":         ["pedal", "petal"],
    "petal":          ["pedal", "peddle"],
    "peer":           ["pier"],
    "pier":           ["peer"],
    "penance":        ["pennants"],
    "pennants":       ["penance"],
    "per":            ["purr"],
    "purr":           ["per"],
    "pi":             ["pie"],
    "pie":            ["pi"],
    "plain":          ["plane"],
    "plane":          ["plain"],
    "plainer":        ["planar", "planer"],
    "planar":         ["plainer", "planer"],
    "planer":         ["plainer", "planar"],
    "plait":          ["plate"],
    "plate":          ["plait"],
    "pleas":          ["please"],
    "please":         ["pleas"],
    "pole":           ["poll"],
    "poll":           ["pole"],
    "poor":           ["pore", "pour"],
    "pore":           ["poor", "pour"],
    "pour":           ["poor", "pore"],
    "populace":       ["populous"],
    "populous":       ["populace"],
    "praise":         ["prays", "preys"],
    "prays":          ["praise", "preys"],
    "preys":          ["praise", "prays"],
    "pray":           ["prey"],
    "prey":           ["pray"],
    "precedence":     ["precedents"],
    "precedents":     ["precedence"],
    "premier":        ["premiere"],
    "premiere":       ["premier"],
    "presence":       ["presents"],
    "presents":       ["presence"],
    "pride":          ["pried"],
    "pried":          ["pride"],
    "prier":          ["prior"],
    "prior":          ["prier"],
    "pries":          ["prize"],
    "prize":          ["pries"],
    "prince":         ["prints"],
    "prints":         ["prince"],
    "principal":      ["principle"],
    "principle":      ["principal"],
    "profit":         ["prophet"],
    "prophet":        ["profit"],
    "rack":           ["wrack"],
    "wrack":          ["rack"],
    "raid":           ["rayed"],
    "rayed":          ["raid"],
    "rail":           ["rale"],
    "rale":           ["rail"],
    "rain":           ["reign", "rein"],
    "reign":          ["rain", "rein"],
    "rein":           ["rain", "reign"],
    "raise":          ["rays", "raze"],
    "rays":           ["raise", "raze"],
    "raze":           ["raise", "rays"],
    "rap":            ["wrap"],
    "wrap":           ["rap"],
    "rapt":           ["wrapped", "wrapt"],
    "wrapped":        ["rapt", "wrapt"],
    "wrapt":          ["rapt", "wrapped"],
    "re-cover":       ["recover"],
    "recover":        ["re-cover"],
    "re-lay":         ["relay"],
    "relay":          ["re-lay"],
    "read":           ["reed"],
    "red":            ["read"],
    "reed":           ["read"],
    "real":           ["reel", "and riel"],
    "reel":           ["real", "and riel"],
    "and riel":       ["real", "reel"],
    "recede":         ["reseed"],
    "reseed":         ["recede"],
    "reek":           ["wreak"],
    "wreak":          ["reek"],
    "residence":      ["residents"],
    "residents":      ["residence"],
    "rest":           ["wrest"],
    "wrest":          ["rest"],
    "retch":          ["wretch"],
    "wretch":         ["retch"],
    "rhyme":          ["rime"],
    "rime":           ["rhyme"],
    "right":          ["rite", "wright", "write"],
    "rite":           ["right", "wright", "write"],
    "wright":         ["right", "rite", "write"],
    "write":          ["right", "rite", "wright"],
    "ring":           ["wring"],
    "wring":          ["ring"],
    "ringer":         ["wringer"],
    "wringer":        ["ringer"],
    "rise":           ["ryes"],
    "ryes":           ["rise"],
    "road":           ["rode", "rowed"],
    "rode":           ["road", "rowed"],
    "rowed":          ["road", "rode"],
    "roe":            ["row"],
    "row":            ["roe"],
    "roil":           ["royal"],
    "royal":          ["roil"],
    "role":           ["roll"],
    "roll":           ["role"],
    "roomer":         ["rumor", "rumour"],
    "rumor":          ["roomer", "rumour"],
    "rumour":         ["roomer", "rumor"],
    "root":           ["route"],
    "route":          ["rout"],
    "rose":           ["rows"],
    "rows":           ["rose"],
    "rote":           ["wrote"],
    "wrote":          ["rote"],
    "rude":           ["rued"],
    "rued":           ["rude"],
    "rues":           ["ruse"],
    "ruse":           ["rues"],
    "rung":           ["wrung"],
    "wrung":          ["rung"],
    "rye":            ["wry"],
    "wry":            ["rye"],
    "sail":           ["sale"],
    "sale":           ["sail"],
    "scene":          ["seen"],
    "seen":           ["scene"],
    "sea":            ["see"],
    "see":            ["sea"],
    "seam":           ["seem"],
    "seem":           ["seam"],
    "sear":           ["seer"],
    "seer":           ["sear"],
    "seas":           ["sees", "seize"],
    "sees":           ["seas", "seize"],
    "seize":          ["seas", "sees"],
    "sects":          ["sex"],
    "sex":            ["sects"],
    "sew":            ["so", "sow"],
    "so":             ["sew", "sow"],
    "sow":            ["sew", "so"],
    "shake":          ["sheik"],
    "shear":          ["sheer"],
    "sheer":          ["shear"],
    "shoe":           ["shoo"],
    "shoo":           ["shoe"],
    "sic":            ["sick"],
    "sick":           ["sic"],
    "sics":           ["six"],
    "six":            ["sics"],
    "side":           ["sighed"],
    "sighed":         ["side"],
    "sighs":          ["size"],
    "size":           ["sighs"],
    "sign":           ["sine"],
    "sine":           ["sign"],
    "slay":           ["sleigh"],
    "sleigh":         ["slay"],
    "sleight":        ["slight"],
    "slight":         ["sleight"],
    "slew":           ["slough"],
    "slough":         ["slew"],
    "soar":           ["sore"],
    "sore":           ["soar"],
    "soared":         ["sword"],
    "sword":          ["soared"],
    "sold":           ["soled"],
    "soled":          ["sold"],
    "sole":           ["soul"],
    "soul":           ["sole"],
    "some":           ["sum"],
    "sum":            ["some"],
    "son":            ["sun"],
    "sun":            ["son"],
    "stair":          ["stare"],
    "stare":          ["stair"],
    "stake":          ["steak"],
    "steak":          ["stake"],
    "stationary":     ["stationery"],
    "stationery":     ["stationary"],
    "steal":          ["steel"],
    "steel":          ["steal"],
    "step":           ["steppe"],
    "steppe":         ["step"],
    "storey":         ["story"],
    "story":          ["storey"],
    "straight":       ["strait"],
    "strait":         ["straight"],
    "suite":          ["sweet"],
    "sweet":          ["suite"],
    "summary":        ["summery"],
    "summery":        ["summary"],
    "tacked":         ["tact"],
    "tact":           ["tacked"],
    "tacks":          ["tax"],
    "tax":            ["tacks"],
    "tail":           ["tale"],
    "tale":           ["tail"],
    "taper":          ["tapir"],
    "tapir":          ["taper"],
    "tarry":          ["terry"],
    "terry":          ["tarry"],
    "taught":         ["taut"],
    "taut":           ["taught"],
    "tea":            ["tee"],
    "tee":            ["tea"],
    "team":           ["teem"],
    "teem":           ["team"],
    "tears":          ["tiers"],
    "tiers":          ["tears"],
    "teas":           ["tease", "tees"],
    "tease":          ["teas", "tees"],
    "tees":           ["teas", "tease"],
    "tense":          ["tents"],
    "tents":          ["tense"],
    "than":           ["then"],
    "then":           ["than"],
    "there":          ["their", "and they're"],
    "their":          ["there", "and they're"],
    "and they're":    ["there", "their"],
    "threw":          ["through"],
    "through":        ["threw"],
    "throne":         ["thrown"],
    "thrown":         ["throne"],
    "thyme":          ["time"],
    "time":           ["thyme"],
    "tide":           ["tied"],
    "tied":           ["tide"],
    "tier":           ["tire"],
    "tire":           ["tier"],
    "tighten":        ["titan"],
    "titan":          ["tighten"],
    "to":             ["too", "and two"],
    "too":            ["to", "and two"],
    "and two":        ["to", "too"],
    "toad":           ["toed", "towed"],
    "toed":           ["toad", "towed"],
    "towed":          ["toad", "toed"],
    "toe":            ["tow"],
    "tow":            ["toe"],
    "told":           ["tolled"],
    "tolled":         ["told"],
    "tracked":        ["tract"],
    "tract":          ["tracked"],
    "tray":           ["trey"],
    "trey":           ["tray"],
    "udder":          ["utter"],
    "utter":          ["udder"],
    "vain":           ["vane", "vein"],
    "vane":           ["vain", "vein"],
    "vein":           ["vain", "vane"],
    "vale":           ["veil"],
    "veil":           ["vale"],
    "vial":           ["vile"],
    "vile":           ["vial"],
    "vice":           ["vise"],
    "vise":           ["vice"],
    "wade":           ["weighed"],
    "weighed":        ["wade"],
    "wail":           ["whale"],
    "whale":          ["wale"],
    "waist":          ["waste"],
    "waste":          ["waist"],
    "wait":           ["weight"],
    "weight":         ["wait"],
    "waive":          ["wave"],
    "wave":           ["waive"],
    "waiver":         ["waver"],
    "waver":          ["waiver"],
    "wale":           ["whale"],
    "war":            ["wore"],
    "wore":           ["war"],
    "ward":           ["warred"],
    "warred":         ["ward"],
    "ware":           ["wear", "and where"],
    "wear":           ["ware", "and where"],
    "and where":      ["ware", "wear"],
    "warn":           ["worn"],
    "worn":           ["warn"],
    "wax":            ["whacks"],
    "whacks":         ["wax"],
    "way":            ["weigh", "whey"],
    "weigh":          ["way", "whey"],
    "whey":           ["way", "weigh"],
    "we":             ["wee"],
    "wee":            ["we"],
    "we'd":           ["weed"],
    "weed":           ["we'd"],
    "we'll":          ["weal", "wheal", "wheel"],
    "weal":           ["we'll", "wheal", "wheel"],
    "wheal":          ["we'll", "weal", "wheel"],
    "wheel":          ["we'll", "weal", "wheal"],
    "we're":          ["were", "whir"],
    "weir":           ["we're"],
    "were":           ["we're", "whir"],
    "whir":           ["we're", "were"],
    "we've":          ["weave"],
    "weave":          ["we've"],
    "weak":           ["week"],
    "week":           ["weak"],
    "wearer":         ["where're"],
    "where're":       ["wearer"],
    "weather":        ["whether"],
    "whether":        ["weather"],
    "wet":            ["whet"],
    "whet":           ["wet"],
    "wheeled":        ["wield"],
    "wield":          ["wheeled"],
    "which":          ["witch"],
    "witch":          ["which"],
    "while":          ["wile"],
    "wile":           ["while"],
    "whiled":         ["wild"],
    "wild":           ["whiled"],
    "whine":          ["wine"],
    "wine":           ["whine"],
    "whined":         ["wind", "wined"],
    "wind":           ["whined", "wined"],
    "wined":          ["whined", "wind"],
    "whirled":        ["world"],
    "world":          ["whirled"],
    "whit":           ["wit"],
    "wit":            ["whit"],
    "whither":        ["wither"],
    "wither":         ["whither"],
    "who's":          ["whose"],
    "whose":          ["who's"],
    "whoa":           ["woe"],
    "woe":            ["whoa"],
    "wood":           ["would"],
    "would":          ["wood"],
    "yack":           ["yak"],
    "yak":            ["yack"],
    "yaw":            ["yore", "you're", "your"],
    "yore":           ["you're", "your"],
    "you're":         ["yore", "your"],
    "your":           ["yore", "you're"],
    "yoke":           ["yolk"],
    "yolk":           ["yoke"],
    "you'll":         ["Yule"],
    "Yule":           ["you'll"],
    "aahed":          ["odd"],
    "odd":            ["aahed"],
    "adieu":          ["ado"],
    "ado":            ["adieu"],
    "ant":            ["aunt"],
    "aunt":           ["ant"],
    "aural":          ["oral"],
    "oral":           ["aural"],
    "err":            ["ere", "air", "heir"],
    "marry":          ["Mary", "merry"],
    "merry":          ["Mary", "marry"],
    "rout":           ["route"],
    "seated":         ["seeded"],
    "seeded":         ["seated"],
    "shone":          ["shown"],
    "shown":          ["shone"],
    "tidal":          ["title"],
    "title":          ["tidal"],
    "trader":         ["traitor"],
    "traitor":        ["trader"],
    "vary":           ["very"],
    "very":           ["vary"],
    "Aaron":          ["Erin"],
    "Erin":           ["Aaron"],
    "Mary":           ["marry", "merry"]
};
